# Problem settings
Problem:
  goal: "point"

# ROM Settings
ROM: 
  # Total energy of POD
  total_energy: 
    # NOTE: lost energy is stated
    primal:
      displacement: 1.e-7
      pressure: 1.e-11
    dual:
      displacement: 1.e-9
      pressure: 1.e-9
  max_iterations: 300
  min_iterations: 20

# FOM settings
FOM: 
  start_time: 0.0
  end_time: 5.0e+6
  delta_t: 1000.0
  force_recompute: False
  mesh_refinement: 2  # factor of uniform refinements
  solver: # iterative solver (used if mesh_refinement > 1)
    tolerance: 5.e-8
    preconditioner: 
      type: "jacobi" # choices: "jacobi", "SOR", "AMG_RG", "AMG_SA"
      max_iter: 1000
      restart: 1000      
    preconditioner_backup:  
      type: "AMG_SA" # choices: "jacobi", "SOR", "AMG_RG", "AMG_SA"
      max_iter: 200
      restart: 200  

INFRASTRUCTURE:
  safe_directory: "results/"